FROM node:4.4.3-slim
# https://hub.docker.com/r/library/node/

RUN apt-get update
RUN apt-get install -y bzip2 libfontconfig pdftk pdfjam

# Download and install phantomjs
WORKDIR /tmp
RUN wget https://us-east.manta.joyent.com//nmajor/public/emailgate/container/phantomjs-2.1.1-linux-x86_64.tar.bz2
RUN tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2
RUN mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /bin/

# Copy pspdftool
COPY container/pspdftool /bin/

RUN apt-get install -y texlive-extra-utils
RUN apt-get install -y texlive-latex-recommended
RUN apt-get install -y poppler-utils

# Copy over app source files
ENV HOME /var/app
RUN mkdir $HOME
WORKDIR $HOME
COPY package.json ./

RUN npm install
RUN npm install -g gulp

COPY . ./
RUN touch ./.env

RUN gulp babel

RUN apt-get install ttf-bitstream-vera
WORKDIR /tmp
RUN wget https://github.com/eosrei/emojione-color-font/releases/download/v1.3/EmojiOneColor-SVGinOT-Linux-1.3.tar.gz
RUN tar zxf EmojiOneColor-SVGinOT-Linux-1.3.tar.gz
WORKDIR EmojiOneColor-SVGinOT-Linux-1.3
RUN ./install.sh

RUN apt-get install unzip
RUN wget https://noto-website.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip
RUN unzip NotoColorEmoji-unhinted.zip -d /usr/share/fonts/truetype/noto
RUN rm -f /usr/share/fonts/truetype/noto/LICENSE_OFL.txt
RUN rm -f /usr/share/fonts/truetype/ancient-scripts/Symbola_hint.ttf
RUN chmod 644 /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf
RUN fc-cache -f -v
RUN rm NotoColorEmoji-unhinted.zip

WORKDIR $HOME

CMD ["node", "dist/index.js"]
